# Site settings
title: Brandon Wang
shorttitle: bw
email: brandonwang@me.com
description: "Graphics Programmer"
baseurl: "/brandonwang.net"
url: "http://brandonwang.net"

# Build settings
markdown: kramdown
permalink: pretty
