# Site settings
title: Brandon Wang
shorttitle: bw
email: brandonwang@me.com
description: "Graphics Programmer"
baseurl: ""
url: "http://brandonwang.net"
future: true

# Build settings
markdown: kramdown
permalink: pretty
